version: '3.8'

services:
  web:
    build: ./
    command: flask run -h 0.0.0.0
    env_file: .env
    ports:
      - 5000:5000
    restart: always
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER
      - POSTGRES_DATABASE
      - POSTGRES_PASSWORD
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
